# Site settings
title: CS Grad Seminar Fall 2020
subtitle: Distributed Systems Verification
baseurl: "/cs_f20" # the subpath of your site, e.g. /blog/
url: "http://gowthamk.github.io" # the base hostname & protocol for your site
syllabus: ""
githubdir: "gowthamk/cs_f20"

# Author/user information
email: gowtham.kaki@colorado.edu
twitter_username: gowthamk
github_username:  gowthamk
authorurl: "https://gowthamk.github.io"
address: |
    Department of Computer Science,
    University of Colorado,
    Boulder, CO 80309

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
